### ISSUE TITLE
Feature request: `addon/index.js` for single-line multiple imports

### ISSUE THREAD

**Issue by lolmaus** [kellyselden/ember-macro-helpers#131] opened 2017-08-24 13:37 UTC
Doing this:

```js
import {computed, raw, writable} from "ember-macro-helpers";
```

is much better than this:

```js
import computed from "ember-macro-helpers/computed";
import raw from "ember-macro-helpers/raw";
import writable from "ember-macro-helpers/writable";
```

**Comment by kellyselden** [comment] 2017-08-24 15:45
Duplicate of #56

I support this.

**Closed by kellyselden** 2017-08-24 15:45 UTC
